In [203]:
import numpy as np
import pandas as pd
import random

In [204]:
popularity = []
for i in range(0,100):
    popularity.append(random.randint(1,10))

In [205]:
data=pd.DataFrame(popularity,cast_crew_rating,columns=['Popularity'])

In [206]:
cast_crew_rating=[]
for i in range(0,100):
    cast_crew_rating.append(popularity[i])
data["Cast_crew_rating"]=cast_crew_rating

In [207]:
theater_rating=[]
for i in range(0,100):
    theater_rating.append(random.randint(1,10))
data['Theater_rating']=theater_rating

In [208]:
seats=['balcony',"first class","second class"]
seat_type=[]
for i in range(0,100):
    seat_type.append(random.choice(seats))
data['Seat_type']=seat_type

In [209]:
time_sh=['morning','afternoon','evening','night']
show_time=[]
for i in range(0,100):
    show_time.append(random.choice(time_sh))
data["show_time"]=show_time

In [210]:
days_bef=[]
for i in range(0,100):
    days_bef.append(random.randint(0,5))
data['days_before']=days_bef

In [211]:
occup=['0%','25%','50%','75%']
occupancy=[]
for i in range(0,100):
    occupancy.append(random.choice(occup))
data['occupancy']=occupancy

In [212]:
data

Popularity  Cast_crew_rating  Theater_rating     Seat_type  show_time  \
10           6                 6               4   first class  afternoon   
10           7                 7              10       balcony    morning   
2            6                 6               9       balcony  afternoon   
6            1                 1               7       balcony    morning   
2            8                 8               1   first class  afternoon   
..         ...               ...             ...           ...        ...   
9            8                 8               4       balcony      night   
7            8                 8               6  second class      night   
9            9                 9               4   first class    morning   
10           4                 4              10       balcony    evening   
6            9                 9               2       balcony    morning   

    days_before occupancy  
10            1       25%  
10            1       25%  
2             0        0%  
6             2       50%  
2             5       50%  
..          ...       ...  
9             1       50%  
7             4       50%  
9             3        0%  
10            1       75%  
6             4       25%  

[100 rows x 7 columns]

In [213]:
def price(a,b,c,d):
    x=0
    if d=='balcony':
        if (a>=7 and b>=7 and c>=7):
            x=500
        elif (a>=7 and b>=7 and (c>=4 and c<7)):
            x=450
        elif (a>=7 and b>=7 and (c>=0 and c<4)):
            x=400
        elif ((a>=4 and a<7) and (b>=4 and b<7) and c>=7):
            x=450
        elif ((a>=4 and a<7) and (b>=4 and b<7) and (c>=4 and c<7)):
            x=400
        elif ((a>=4 and a<7) and (b>=4 and b<7) and (c>=0 and c<4)):
            x=350
        elif ((a>=0 and a<4) and (b>=0 and b<4) and c>=7):
            x=400
        elif ((a>=0 and a<4) and (b>=0 and b<4) and (c>=4 and c<7)):
            x=350
        elif ((a>=0 and a<4) and (b>=0 and b<4) and (c>=0 and c<4)):
            x=300
        else:
            x=50
    elif d=='first class':
        if (a>=7 and b>=7 and c>=7):
            x=400
        elif (a>=7 and b>=7 and (c>=4 and c<7)):
            x=350
        elif (a>=7 and b>=7 and (c>=0 and c<4)):
            x=300
        elif ((a>=4 and a<7) and (b>=4 and b<7) and c>=7):
            x=350
        elif ((a>=4 and a<7) and (b>=4 and b<7) and (c>=4 and c<7)):
            x=300
        elif ((a>=4 and a<7) and (b>=4 and b<7) and (c>=0 and c<4)):
            x=250
        elif ((a>=0 and a<4) and (b>=0 and b<4) and c>=7):
            x=300
        elif ((a>=0 and a<4) and (b>=0 and b<4) and (c>=4 and c<7)):
            x=250
        elif ((a>=0 and a<4) and (b>=0 and b<4) and (c>=0 and c<4)):
            x=200
        else:
            x=50
    elif d=="second class":
        if (a>=7 and b>=7 and c>=7):
            x=300
        elif (a>=7 and b>=7 and (c>=4 and c<7)):
            x=250
        elif (a>=7 and b>=7 and (c>=0 and c<4)):
            x=200
        elif ((a>=4 and a<7) and (b>=4 and b<7) and c>=7):
            x=250
        elif ((a>=4 and a<7) and (b>=4 and b<7) and (c>=4 and c<7)):
            x=200
        elif ((a>=4 and a<7) and (b>=4 and b<7) and (c>=0 and c<4)):
            x=150
        elif ((a>=0 and a<4) and (b>=0 and b<4) and c>=7):
            x=200
        elif ((a>=0 and a<4) and (b>=0 and b<4) and (c>=4 and c<7)):
            x=150
        elif ((a>=0 and a<4) and (b>=0 and b<4) and (c>=0 and c<4)):
            x=100
        else:
            x=50

    return x

In [214]:
price1=[]
for i in range(0,100):
    price1.append(price(popularity[i],cast_crew_rating[i],theater_rating[i],seat_type[i]))
data["Price"]=price1

In [215]:
data

Popularity  Cast_crew_rating  Theater_rating     Seat_type  show_time  \
10           6                 6               4   first class  afternoon   
10           7                 7              10       balcony    morning   
2            6                 6               9       balcony  afternoon   
6            1                 1               7       balcony    morning   
2            8                 8               1   first class  afternoon   
..         ...               ...             ...           ...        ...   
9            8                 8               4       balcony      night   
7            8                 8               6  second class      night   
9            9                 9               4   first class    morning   
10           4                 4              10       balcony    evening   
6            9                 9               2       balcony    morning   

    days_before occupancy  Price  
10            1       25%    300  
10            1       25%    500  
2             0        0%    450  
6             2       50%    400  
2             5       50%    300  
..          ...       ...    ...  
9             1       50%    450  
7             4       50%    250  
9             3        0%    350  
10            1       75%    450  
6             4       25%    400  

[100 rows x 8 columns]

In [216]:
data1=data[["Popularity","Cast_crew_rating","Theater_rating","Seat_type","Price"]]
data1

Popularity  Cast_crew_rating  Theater_rating     Seat_type  Price
10           6                 6               4   first class    300
10           7                 7              10       balcony    500
2            6                 6               9       balcony    450
6            1                 1               7       balcony    400
2            8                 8               1   first class    300
..         ...               ...             ...           ...    ...
9            8                 8               4       balcony    450
7            8                 8               6  second class    250
9            9                 9               4   first class    350
10           4                 4              10       balcony    450
6            9                 9               2       balcony    400

[100 rows x 5 columns]

In [217]:
seats={"balcony":1,"first class":2,"second class":3}
data2=data1.replace({"Seat_type":seats})
data2

Popularity  Cast_crew_rating  Theater_rating  Seat_type  Price
10           6                 6               4          2    300
10           7                 7              10          1    500
2            6                 6               9          1    450
6            1                 1               7          1    400
2            8                 8               1          2    300
..         ...               ...             ...        ...    ...
9            8                 8               4          1    450
7            8                 8               6          3    250
9            9                 9               4          2    350
10           4                 4              10          1    450
6            9                 9               2          1    400

[100 rows x 5 columns]

In [218]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder

ct=ColumnTransformer(transformers=[('encoder',OneHotEncoder(),[3])],remainder='passthrough')
data3=ct.fit_transform(data2)

In [219]:
data3

array([[  0.,   1.,   0.,   6.,   6.,   4., 300.],
       [  1.,   0.,   0.,   7.,   7.,  10., 500.],
       [  1.,   0.,   0.,   6.,   6.,   9., 450.],
       [  1.,   0.,   0.,   1.,   1.,   7., 400.],
       [  0.,   1.,   0.,   8.,   8.,   1., 300.],
       [  1.,   0.,   0.,   8.,   8.,   3., 400.],
       [  0.,   0.,   1.,   7.,   7.,   3., 200.],
       [  1.,   0.,   0.,   9.,   9.,   6., 450.],
       [  0.,   0.,   1.,   5.,   5.,   3., 150.],
       [  0.,   0.,   1.,  10.,  10.,   2., 200.],
       [  0.,   0.,   1.,  10.,  10.,   2., 200.],
       [  0.,   0.,   1.,   8.,   8.,   3., 200.],
       [  0.,   1.,   0.,   5.,   5.,   4., 300.],
       [  1.,   0.,   0.,  10.,  10.,   1., 400.],
       [  0.,   1.,   0.,   2.,   2.,   9., 300.],
       [  0.,   0.,   1.,   8.,   8.,   1., 200.],
       [  0.,   1.,   0.,   8.,   8.,  10., 400.],
       [  1.,   0.,   0.,   6.,   6.,   2., 350.],
       [  0.,   0.,   1.,   8.,   8.,   9., 300.],
       [  1.,   0.,   0.,   2.,

In [220]:
cols=['balcony','first class','second class','Popularity','Cast_crew_rating','Theater_rating','Price']
data4=pd.DataFrame(data3,columns=cols)

In [221]:
data4

balcony  first class  second class  Popularity  Cast_crew_rating  \
0       0.0          1.0           0.0         6.0               6.0   
1       1.0          0.0           0.0         7.0               7.0   
2       1.0          0.0           0.0         6.0               6.0   
3       1.0          0.0           0.0         1.0               1.0   
4       0.0          1.0           0.0         8.0               8.0   
..      ...          ...           ...         ...               ...   
95      1.0          0.0           0.0         8.0               8.0   
96      0.0          0.0           1.0         8.0               8.0   
97      0.0          1.0           0.0         9.0               9.0   
98      1.0          0.0           0.0         4.0               4.0   
99      1.0          0.0           0.0         9.0               9.0   

    Theater_rating  Price  
0              4.0  300.0  
1             10.0  500.0  
2              9.0  450.0  
3              7.0  400.0  
4              1.0  300.0  
..             ...    ...  
95             4.0  450.0  
96             6.0  250.0  
97             4.0  350.0  
98            10.0  450.0  
99             2.0  400.0  

[100 rows x 7 columns]

In [222]:
x=data4.iloc[:,:-1].values
y=data4.iloc[:,-1].values.reshape(-1,1)

In [223]:
x

array([[ 0.,  1.,  0.,  6.,  6.,  4.],
       [ 1.,  0.,  0.,  7.,  7., 10.],
       [ 1.,  0.,  0.,  6.,  6.,  9.],
       [ 1.,  0.,  0.,  1.,  1.,  7.],
       [ 0.,  1.,  0.,  8.,  8.,  1.],
       [ 1.,  0.,  0.,  8.,  8.,  3.],
       [ 0.,  0.,  1.,  7.,  7.,  3.],
       [ 1.,  0.,  0.,  9.,  9.,  6.],
       [ 0.,  0.,  1.,  5.,  5.,  3.],
       [ 0.,  0.,  1., 10., 10.,  2.],
       [ 0.,  0.,  1., 10., 10.,  2.],
       [ 0.,  0.,  1.,  8.,  8.,  3.],
       [ 0.,  1.,  0.,  5.,  5.,  4.],
       [ 1.,  0.,  0., 10., 10.,  1.],
       [ 0.,  1.,  0.,  2.,  2.,  9.],
       [ 0.,  0.,  1.,  8.,  8.,  1.],
       [ 0.,  1.,  0.,  8.,  8., 10.],
       [ 1.,  0.,  0.,  6.,  6.,  2.],
       [ 0.,  0.,  1.,  8.,  8.,  9.],
       [ 1.,  0.,  0.,  2.,  2.,  1.],
       [ 0.,  0.,  1.,  8.,  8.,  9.],
       [ 0.,  1.,  0.,  1.,  1., 10.],
       [ 1.,  0.,  0.,  2.,  2.,  5.],
       [ 1.,  0.,  0.,  8.,  8.,  2.],
       [ 1.,  0.,  0.,  4.,  4.,  4.],
       [ 0.,  1.,  0.,  3

In [224]:
y

array([[300.],
       [500.],
       [450.],
       [400.],
       [300.],
       [400.],
       [200.],
       [450.],
       [150.],
       [200.],
       [200.],
       [200.],
       [300.],
       [400.],
       [300.],
       [200.],
       [400.],
       [350.],
       [300.],
       [300.],
       [300.],
       [300.],
       [350.],
       [400.],
       [400.],
       [200.],
       [400.],
       [350.],
       [200.],
       [150.],
       [200.],
       [250.],
       [350.],
       [300.],
       [450.],
       [300.],
       [450.],
       [300.],
       [500.],
       [400.],
       [300.],
       [200.],
       [300.],
       [200.],
       [300.],
       [200.],
       [300.],
       [250.],
       [150.],
       [300.],
       [250.],
       [100.],
       [100.],
       [450.],
       [400.],
       [300.],
       [350.],
       [500.],
       [150.],
       [400.],
       [400.],
       [350.],
       [400.],
       [200.],
       [450.],
       [300.],
       [30

In [225]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.2,random_state=0)

In [226]:
from sklearn.linear_model import LinearRegression
reg1=LinearRegression()
reg1.fit(x_train,y_train)

LinearRegression()

In [227]:
y_pred1=reg1.predict(x_test)
y_pred1

array([[395.90541471],
       [222.57028347],
       [464.3724693 ],
       [290.95778604],
       [438.49755653],
       [236.67455628],
       [408.84287109],
       [201.66488346],
       [394.73859828],
       [423.22646729],
       [434.99710725],
       [438.49755653],
       [306.3084273 ],
       [410.28901091],
       [466.12269394],
       [173.45633783],
       [349.20465395],
       [364.47574319],
       [278.09988167],
       [161.68569788]])

In [228]:
y_test

array([[400.],
       [200.],
       [450.],
       [300.],
       [400.],
       [200.],
       [400.],
       [200.],
       [400.],
       [450.],
       [450.],
       [400.],
       [300.],
       [400.],
       [450.],
       [200.],
       [350.],
       [400.],
       [300.],
       [150.]])

In [230]:
from sklearn.ensemble import RandomForestRegressor
reg2=RandomForestRegressor(n_estimators=100,random_state=0)
reg2.fit(x_train,y_train)

C:\Users\MEDHA TRUST\AppData\Local\Temp\ipykernel_3652\3099673457.py:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  reg2.fit(x_train,y_train)


RandomForestRegressor(random_state=0)

In [231]:
y_pred2=reg2.predict(x_test)
y_pred2=y_pred2.reshape(-1,1)
y_pred2

array([[385.5],
       [215.5],
       [451. ],
       [297.5],
       [405. ],
       [214.5],
       [370.5],
       [196.5],
       [370.5],
       [410. ],
       [450. ],
       [405. ],
       [335.5],
       [388. ],
       [445.5],
       [198.5],
       [384.5],
       [384.5],
       [322.5],
       [186.5]])

In [232]:
reg2.score(x_test,y_test)

0.9545777202072538

In [244]:
from sklearn.metrics import r2_score
r2_score(y_pred1,y_test)

0.9526547207036105

In [234]:
def predict_price(seat_t,pop,cast,talk):
    pred_array=[]
    if seat_t=="balcony":
        pred_array=pred_array+[1,0,0]
    elif seat_t=="first class":
        pred_array=pred_array+[0,1,0]
    elif seat_t=="second class":
        pred_array=pred_array+[0,0,1]

    pred_array=pred_array+[pop,cast,talk]
    pred_array=np.array([pred_array])
    pred=reg2.predict(pred_array)
    return int(round(pred[0]))

In [235]:
predict_price("second class",1,1,7)

187